spring:
  profiles:
    active: a
  rabbitmq:
    host: 47.105.58.171
    port: 5672
    username: admin
    password: 123456
  redis:
    database: 0
    password: 123456
    host: 47.105.58.171
    port: 6379